apiVersion: apps/v1
kind: Deployment
metadata:
  name: ViewPage
  labels:
    app: ViewPage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ViewPage
  template:
    metadata:
      labels:
        app: ViewPage
    spec:
      containers:
        - name: ViewPage
          image: username/ViewPage:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5